tutor_accounting/accounting/urls.py
from django.urls import path
from .views import (
    students, students_detail, schedule,
    schedule_detail, profile
)

app_name = "accounting"

urlpatterns = [
    path("students/", students, name="students"),
    path("students/<int:pk>/", students_detail, name="students_detail"),
    path("schedule/", schedule, name="schedule"),
    path("schedule/<int:pk>_<str:date>_<str:time>", schedule_detail, name="schedule_detail"),
    path("profile/", profile, name="profile"),
]

tutor_accounting/tutor_accounting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounting.urls", namespace="accounting")),
    path("users/", include("users.urls", namespace="users")),
]

tutor_accounting/users/urls.py
from django.contrib.auth.views import (
    # LoginView,
    LogoutView,
)
from django.urls import path
from .views import SignIn

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),
    path(
        'signin/',
        SignIn,
        name='signin'
    )
]

tutor_accounting/accounting/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Student(models.Model):
    first_name = models.CharField(
        max_length=50,
        verbose_name="Имя",
    )
    last_name = models.CharField(
        max_length=50,
        verbose_name="Фамилия",
        blank=True,
        null=True,
    )
    cost = models.IntegerField(
        default=1000,
        verbose_name="Стоимость часа"
    )
    balance = models.IntegerField(
        default=0,
        verbose_name="Баланс"
    )

    class Meta:
        verbose_name = "Ученик"
        verbose_name_plural = "Ученики"

    def __str__(self):
        return self.first_name


class Lesson(models.Model):
    student = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name="Ученик"
    )
    tutor = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="tutor",
        verbose_name="Преподаватель"
    )
    date = models.DateTimeField(
        verbose_name="Дата проведения занятия"
    )
    paid_for = models.BooleanField(
        default=False,
        verbose_name="Оплачено"
    )
    conducted = models.BooleanField(
        default=False,
        verbose_name="Проведено"
    )
    is_cancelled = models.BooleanField(
        default=False,
        verbose_name="Отменено"
    )

    class Meta:
        verbose_name = "Занятие"
        verbose_name_plural = "Занятия"

    def __str__(self):
        return f"Занятие {self.student} {self.date}"


class LessonAccounting(models.Model):
    month = models.CharField(
        max_length=50,
        verbose_name="Месяц"
    )
    year = models.CharField(
        max_length=50,
        verbose_name="Год"
    )
    quantity_conducted = models.IntegerField(
        default=0,
        verbose_name="Количество проведенных"
    )
    quantity_paid = models.IntegerField(
        default=0,
        verbose_name="Количество оплаченных"
    )
    quantity_cancelled = models.IntegerField(
        default=0,
        verbose_name="Количество отменённых"
    )
    quantity_moved = models.IntegerField(
        default=0,
        verbose_name="Количество перенесённых"
    )

    class Meta:
        verbose_name = "Учёт занятий"
        verbose_name_plural = "Учёты занятий"


class Payment(models.Model):
    student = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name="Ученик"
    )
    date = models.DateField(
        verbose_name="Месяц и год оплаты"
    )
    amount = models.IntegerField(
        default=0,
        verbose_name="Сумма"
    )

    class Meta:
        verbose_name = "Оплата"
        verbose_name_plural = "Оплаты"

    def __str__(self):
        return f"Оплата {self.student} за {self.date}"


class CreateSchedule(models.Model):
    is_created = models.BooleanField(
        default=False,
        verbose_name="Расписание создано на текущую неделю"
    )
    week_number = models.IntegerField(
        default=0,
        verbose_name="Номер недели"
    )

tutor_accounting/accounting/views.py
from django.shortcuts import render
from .models import (
    Student, Lesson, Payment,
    CreateSchedule, LessonAccounting
)

from django.contrib.auth import get_user_model
from users.models import Schedule

import datetime
from django.contrib.admin.views.decorators import staff_member_required

User = get_user_model()


def get_week_days(year=datetime.datetime.today().year, week=datetime.datetime.now().isocalendar()[1]):
    # Находим первый день года
    first_day_of_year = datetime.datetime(year, 1, 1)

    # Находим первый день нужной недели
    first_weekday = first_day_of_year + datetime.timedelta(weeks=week - 1)

    # Получаем список дней недели
    week_days = []
    weekdays = {
        0: "Понедельник",
        1: "Вторник",
        2: "Среда",
        3: "Четверг",
        4: "Пятница",
        5: "Суббота",
        6: "Воскресенье",
    }
    for i in range(7):
        a = first_weekday + datetime.timedelta(days=i)
        b = Schedule.objects.filter(weekday=weekdays.get(i))
        elem = [f'{weekdays.get(i)} {a.strftime("%Y-%m-%d")}', sorted(b, key=lambda x: x.time)]
        week_days.append(elem)
    return week_days


@staff_member_required
def students(request):
    students_all = User.objects.filter(is_student=True)
    return render(
        request,
        "accounting/students.html",
        {
            "students": students_all
        }
    )


@staff_member_required
def students_detail(request, pk):
    student = User.objects.get(pk=pk)
    return render(
        request,
        "accounting/students_detail.html",
        {
            "student": student
        }
    )


@staff_member_required
def schedule(request):
    week = datetime.datetime.now().isocalendar()[1]
    schedule_all = get_week_days()
    if not CreateSchedule.objects.filter(week_number=week):
        for elem in schedule_all:
            for people in elem[1]:
                data = {
                    "student": people.student,
                    "date": f"{elem[0].split()[1]} {str(people.time)}"
                }
                Lesson.objects.create(**data)
        CreateSchedule.objects.create(week_number=week, is_created=True)
    else:
        print(True)

    return render(
        request,
        "accounting/schedule.html",
        {
            "week": schedule_all
        }
    )


@staff_member_required
def schedule_detail(request, pk, date, time):
    date_time = f"{date.split()[1]} {time}"
    student = User.objects.get(pk=pk)
    lesson = Lesson.objects.filter(student=student, date=date_time)
    if request.method == "POST":
        obj, created = LessonAccounting.objects.get_or_create(
            month=datetime.datetime.now().month,
            year=datetime.datetime.now().year,
        )
        if request.POST.get("action") == "conducted":
            lesson.update(conducted=True)
            obj.quantity_conducted += 1
            student.balance -= student.cost
        elif request.POST.get("action") == "paid":
            lesson.update(paid_for=True)
            obj.quantity_paid += 1
            student.balance += student.cost
        elif request.POST.get("action") == "move":
            pass
        elif request.POST.get("action") == "cancel":
            lesson.update(is_cancelled=True)
            obj.quantity_cancelled += 1
        student.save()
        obj.save()
    return render(
        request,
        "accounting/schedule_detail.html",
        {
            "lesson": lesson[0],
            "date": date,
            "time": time
        }
    )


def profile(request):
    return render(request, "accounting/profile.html")

tutor_accounting/templates/accounting/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

tutor_accounting/templates/accounting/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Профиль
{% endblock %}

{% block content %}
    <section class="w-100 px-4 py-5" style="background-color: #9de2ff; border-radius: .5rem .5rem 0 0;">
  <div class="row d-flex justify-content-center">
    <div class="col col-md-9 col-lg-7 col-xl-6">
      <div class="card" style="border-radius: 15px;">
        <div class="card-body p-4">
          <div class="d-flex">
            <div class="flex-shrink-0">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-1.webp"
                alt="Generic placeholder image" class="img-fluid" style="width: 180px; border-radius: 10px;">
            </div>
            <div class="flex-grow-1 ms-3">
              <h5 class="mb-1">{{ user.first_name }}{% if user.last_name %} {{ user.last_name }} {% endif %}</h5>
              <p class="mb-2 pb-1">{% if user.is_student %} Ученик {% else %} Преподаватель {% endif %}</p>
              <div class="d-flex justify-content-start rounded-3 p-2 mb-2 bg-body-tertiary">
                <div>
                  <p class="small text-muted mb-1">Баланс</p>
                  <p class="mb-0">{{ user.balance }}</p>

                </div>
                <div class="px-3">
                  <p class="small text-muted mb-1">Followers</p>
                  <p class="mb-0">976</p>
                </div>
                <div>
                  <p class="small text-muted mb-1">Rating</p>
                  <p class="mb-0">8.5</p>
                </div>
              </div>
              <div class="d-flex pt-1">
                <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-primary me-1 flex-grow-1">Chat</button>
                <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary flex-grow-1">Follow</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

tutor_accounting/templates/accounting/schedule.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Расписание занятий
{% endblock %}

{% block content %}
    {% block static %}
        <link rel="stylesheet" href={% static "css/style.css" %}>
    {% endblock %}

{#    <link rel="stylesheet" type="text/css"#}
{#          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">#}
{#    <div class="container animated animated-done bootdey" data-animate="fadeIn" data-animate-delay="0.05"#}
{#         style="animation-delay: 0.05s;">#}
{#        <hr class="hr-lg mt-0 mb-2 w-10 mx-auto hr-primary">#}
{#        <h2 class="text-slab text-center text-uppercase mt-0 mb-5">#}
{#            Расписание занятий#}
{#        </h2>#}
{#        <div class="timeline timeline-left mx-lg-10">#}
{#{% for day, schedule in week %}#}
{#        <div class="timeline-breaker timeline-breaker-middle">{{ day }}</div>#}
{#    {% if not schedule %}#}
{#            <div class="timeline-item mt-3 row text-center p-2">#}
{#                <div class="col font-weight-bold text-md-right"></div>#}
{#                <div class="col-1">Выходной</div>#}
{#                <div class="col font-weight-bold text-md-left"></div>#}
{#                <div class="col-12 text-xs text-muted"></div>#}
{#            </div>#}
{#        {% endif %}#}
{#    {% for elem in schedule %}#}
{##}
{#            <div class="timeline-item mt-3 row text-center p-2">#}
{#                <div class="col font-weight-bold text-md-right"></div>#}
{#                <div class="col-1"><a href="{% url "accounting:schedule_detail" elem.student.pk day elem.time %}">{{ elem.student }} {{ elem.time }}</a></div>#}
{#                <div class="col font-weight-bold text-md-left"></div>#}
{#                <div class="col-12 text-xs text-muted"></div>#}
{#            </div>#}
{#        {% endfor %}#}
{#        {% endfor %}#}
{#        </div>#}
{#    </div>#}
    <div class="container py-5">
    {% for day, schedule in week %}
        <h3 class="text-center mb-4">{{ day }}</h3>
        <ul class="list-group">
        {% if not schedule %}
            <li class="list-group-item">
                    <a class="text-decoration-none">Выходной</a>
                </li>
        {% endif %}
            {% for elem in schedule %}
                <li class="list-group-item">
                    <a href="{% url "accounting:schedule_detail" elem.student.pk day elem.time %}" class="text-decoration-none">{{ elem.time }} - {{ elem.student.first_name }}{% if elem.student.last_name %} {{ elem.student.last_name }} {% endif %}</a>
                </li>
            {% endfor %}
        </ul>
    {% endfor %}
    </div>
{% endblock %}

tutor_accounting/templates/accounting/schedule_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Расписание занятий | NAME
{% endblock %}

{% block content %}
    <hr class="hr-lg mt-0 mb-2 w-10 mx-auto hr-primary">
<h2 class="text-slab text-center text-uppercase mt-0 mb-5">
            ЗАНЯТИЕ | {{ lesson.student.first_name }} {% if lesson.student.last_name %} {{ lesson.student.last_name }} {% endif %}
        </h2>
    <h4 class="text-slab text-center text-uppercase mt-0 mb-5">{{ date }} - {{ time }}</h4>



    <div class="card text-center">
  <div class="card-header">
  {% if lesson.is_cancelled %}
  Отменено
  {% else %}
    {% if lesson.conducted %} Проведено {% else %} Не проведено {% endif %} | {% if lesson.paid_for %} Оплачено {% else %} Не оплачено {% endif %}
  {% endif %}
  </div>
  <div class="card-body">
    <h5 class="card-title">Занятие | {{ lesson.student.first_name }} {% if lesson.student.last_name %} {{ lesson.student.last_name }} {% endif %}</h5>
    <p class="card-text">С вспомогательным текстом ниже в качестве естественного перехода к дополнительному контенту.</p>
  <form method="POST">
  {% csrf_token %}
    {% if lesson.conducted or lesson.is_cancelled %}
        <button type="submit" class="btn btn-secondary" disabled>Проведено</button>
    {% else %}
        <button type="submit" name="action" value="conducted" class="btn btn-danger">Проведено</button>
    {% endif %}
      {% if lesson.paid_for or lesson.is_cancelled %}
          <button type="submit" class="btn btn-secondary" disabled>Оплачено</button>
      {% else %}
          <button type="submit" name="action" value="paid" class="btn btn-danger">Оплачено</button>
      {% endif %}
  <br>
  <br>
  {% if lesson.conducted  or lesson.is_cancelled %}
      <button type="submit" name="action" value="move" class="btn btn-secondary" disabled>Перенести</button>
      <button type="submit" name="action" value="cancel" class="btn btn-secondary" disabled>Отменить</button>
  {% else %}
    <button type="submit" name="action" value="move" class="btn btn-warning">Перенести</button>
      <button type="submit" name="action" value="cancel" class="btn btn-warning">Отменить</button>
  {% endif %}
  </form>

  </div>
  <div class="card-footer text-muted">
    2 дня спустя
  </div>
</div>
{% endblock %}

tutor_accounting/templates/accounting/students.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Ученики
{% endblock %}

{% block content %}
    <div class="container py-5">
        <h3 class="text-center mb-4">Ученики:</h3>
        <ul class="list-group">
            {% for student in students %}
                <li class="list-group-item">
                    <a href="{% url "accounting:students_detail" student.pk %}" class="text-decoration-none">{{ student.first_name }}{% if student.last_name %} {{ student.last_name }} {% endif %}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

tutor_accounting/templates/accounting/students_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Ученик: {{ student.first_name }}
{% endblock %}

{% block content %}

    <div class="container py-5">
        <h3 class="text-center mb-4">Ученик | {{ student.first_name }}{% if lesson.student.last_name %} {{ lesson.student.last_name }} {% endif %}</h3>
        <ul class="list-group">
                <li class="list-group-item">
                    <a class="text-decoration-none">Стоимость часа: {{ student.cost }}</a>
                </li>
            <li class="list-group-item">
                    <a class="text-decoration-none">Баланс: {{ student.balance }}</a>
                </li>
        </ul>
    </div>
{% endblock %}