tutor_accounting/accounting/urls.py
from django.urls import path
from .views import (
    students, students_detail, schedule,
    schedule_detail, profile
)

app_name = "accounting"

urlpatterns = [
    path("students/", students, name="students"),
    path("students/<int:pk>/", students_detail, name="students_detail"),
    path("schedule/", schedule, name="schedule"),
    path("schedule/<int:pk>_<str:date>_<str:time>", schedule_detail, name="schedule_detail"),
    path("profile/", profile, name="profile"),
]

tutor_accounting/tutor_accounting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounting.urls", namespace="accounting")),
    path("users/", include("users.urls", namespace="users")),
]

tutor_accounting/users/urls.py
from django.contrib.auth.views import (
    # LoginView,
    LogoutView,
)
from django.urls import path
from .views import SignIn

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),
    path(
        'signin/',
        SignIn,
        name='signin'
    )
]

tutor_accounting/templates/includes/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

tutor_accounting/templates/includes/header.html
{% if user.is_authenticated %}
<header>
    <nav class="py-2 bg-light border-bottom">
    <div class="container d-flex flex-wrap">
      <ul class="nav me-auto">
        <li class="nav-item"><a href="{% url "accounting:students" %}" class="nav-link link-dark px-2 " aria-current="page">Ученики</a></li>
        <li class="nav-item"><a href="{% url "accounting:schedule" %}" class="nav-link link-dark px-2">Расписание</a></li>
      </ul>
      <ul class="nav">

            {% if user.is_authenticated %}
                <li class="nav-item"><a href="#" class="nav-link link-dark px-2">{{ user.username }}</a></li>
                <li class="nav-item"><a href="{% url "users:logout" %}" class="nav-link link-dark px-2">Выход</a></li>
            {% else %}
            <li class="nav-item"><a href="{% url "users:signin" %}" class="nav-link link-dark px-2">Вход</a></li>
            {% endif %}
      </ul>
    </div>
  </nav>
</header>
{% endif %}